version: "3.9"

services:
  mariadb:
    env_file: .env
    container_name: mariadb_container
    build: ./requirements/mariadb
    networks:
      - default
    volumes:
      - mariadb:/var/lib/mysql/
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASS=${DB_PASS}
      - MARIADB_NAME=${DB_NAME}
    restart: unless-stopped

  wordpress:
    container_name: wp_container
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress/
    depends_on:
      - mariadb
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASS=${DB_PASS}
      - MARIADB_NAME=${DB_NAME}
      - MARIADB_HOST=${DB_HOST}
    networks:
      - default
    restart: unless-stopped
  
  nginx:
    container_name: nginx_container
    build: ./requirements/nginx
    extra_hosts:
      - "pdiaz-pa.42fr.com:127.0.0.1"
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - default
    volumes:
      - wordpress:/var/www/wordpress/
    links:
      - wordpress

volumes:
  mariadb:
    name: mdbvolume
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/pdiaz-pa/data/mariadb'
  wordpress:
    name: wpvolume
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/pdiaz-pa/data/wordpress' 
