networks:
  localhost: 
    name: inception_network
services:
  nginx:
    container_name: nginx_container
    build: ./requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - localhost
  wordpress:
    container_name: wp_container
    build: ./requirements/wordpress
    restart: unless-stopped
    networks:
      - localhost
  mariadb:
    container_name: mariadb_container
    build: ./requirements/mariadb
    restart: unless-stopped
    networks:
      - localhost