volumes:
  wordpress:
    name: wordpress
  database:
    name: database

services:
  mariadb:
    container_name: mariadb_container
    build: ./requirements/mariadb
    networks:
      - default
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: caldodepollo
      MYSQL_DATABASE: wp_db
      MYSQL_USER: pdiaz-pa
      MYSQL_PASSWORD: caldodepollo
    restart: unless-stopped
  wordpress:
    container_name: wp_container
    build: ./requirements/wordpress
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      MYSQL_ROOT_PASSWORD: caldodepollo
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_USER: pdiaz-pa
      WORDPRESS_DB_PASSWORD: caldodepollo
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mariadb
    networks:
      - default
    restart: unless-stopped
  nginx:
    container_name: nginx_container
    build: ./requirements/nginx
    extra_hosts:
      - "pdiaz-pa.42fr.com:127.0.0.1"
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - default
    volumes:
      - wordpress:/var/www/wordpress
    links:
      - wordpress


